source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DeepGram_Example', :exclusive => true do
  pod 'DeepGram', :path => '../'
end

target 'DeepGram_Tests', :exclusive => true do
  pod 'DeepGram', :path => '../'

  
end
